# Generated by Django 4.1.3 on 2022-12-18 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cake_designing', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake_designing',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders'),
        ),
        migrations.AddField(
            model_name='cake_designing',
            name='taste_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cake_designing.taste'),
        ),
    ]
