# Generated by Django 4.1.3 on 2022-12-04 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cake_designing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake_designing',
            name='basemodel_ptr',
        ),
        migrations.RemoveField(
            model_name='cake_designing',
            name='feeling_name',
        ),
        migrations.RemoveField(
            model_name='cake_designing',
            name='taste_name',
        ),
        migrations.RemoveField(
            model_name='feeling',
            name='basemodel_ptr',
        ),
        migrations.RemoveField(
            model_name='taste',
            name='basemodel_ptr',
        ),
    ]
