# Generated by Django 4.1.3 on 2022-12-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cake_designing', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeling',
            name='feeling_name',
        ),
        migrations.RemoveField(
            model_name='taste',
            name='Taste_name',
        ),
        migrations.AddField(
            model_name='feeling',
            name='feeling_name_en',
            field=models.CharField(default=0, max_length=100, verbose_name='feeling_name'),
        ),
        migrations.AddField(
            model_name='feeling',
            name='feeling_name_fa',
            field=models.CharField(default=0, max_length=100, verbose_name='feeling_name'),
        ),
        migrations.AddField(
            model_name='taste',
            name='taste_name_en',
            field=models.CharField(default=0, max_length=100, verbose_name='Taste_name'),
        ),
        migrations.AddField(
            model_name='taste',
            name='taste_name_fa',
            field=models.CharField(default=0, max_length=100, verbose_name='Taste_name'),
        ),
    ]
