# Generated by Django 4.1.3 on 2022-12-04 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_feeling_taste_orders_order_item_cake_designing_and_more'),
        ('Cake_designing', '0002_remove_cake_designing_basemodel_ptr_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cake_Designing',
        ),
        migrations.DeleteModel(
            name='Feeling',
        ),
        migrations.DeleteModel(
            name='Taste',
        ),
    ]
