# Generated by Django 4.1.3 on 2022-12-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cake_designing', '0003_remove_feeling_feeling_name_remove_taste_taste_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeling',
            name='feeling_name_en',
            field=models.CharField(max_length=100, verbose_name='feeling_name'),
        ),
        migrations.AlterField(
            model_name='feeling',
            name='feeling_name_fa',
            field=models.CharField(max_length=100, verbose_name='feeling_name'),
        ),
        migrations.AlterField(
            model_name='taste',
            name='taste_name_en',
            field=models.CharField(max_length=100, verbose_name='Taste_name'),
        ),
        migrations.AlterField(
            model_name='taste',
            name='taste_name_fa',
            field=models.CharField(max_length=100, verbose_name='Taste_name'),
        ),
    ]
