# Generated by Django 4.1.3 on 2022-12-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cake_designing', '0004_alter_feeling_feeling_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake_designing',
            name='total_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
