# Generated by Django 4.1.3 on 2022-12-06 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cake_designing', '0005_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cake_designing',
            old_name='discription',
            new_name='description',
        ),
    ]
