# Generated by Django 4.1.3 on 2022-12-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cake_designing', '0006_rename_discription_cake_designing_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake_designing',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
