# Generated by Django 4.1.3 on 2022-12-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cake_designing', '0007_alter_cake_designing_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake_designing',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cake_designing',
            name='extra_payment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cake_designing',
            name='print_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cake_designing',
            name='ready_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cake_designing',
            name='sample_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
