# Generated by Django 4.1.3 on 2022-12-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_account',
            name='card_bank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
