# Generated by Django 4.1.3 on 2022-12-04 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
