# Generated by Django 4.1.3 on 2022-12-04 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_user_managers_remove_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bank_account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.bank_account'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.profile'),
        ),
    ]
