# Generated by Django 4.1.3 on 2022-12-17 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('profile_view', 'can his profile')]},
        ),
    ]
