# Generated by Django 4.1.3 on 2022-12-17 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('owner_profile_view', 'can his profile')]},
        ),
    ]
