# Generated by Django 4.1.3 on 2022-12-17 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_discount_category_id'),
        ('orders', '0002_alter_order_item_discription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='discount_code_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.discount_code'),
        ),
    ]
