# Generated by Django 4.1.3 on 2023-01-01 17:57

from django.db import migrations, models
import orders.validators


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orders_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[orders.validators.test]),
        ),
    ]
