# Generated by Django 4.1.3 on 2023-01-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orders_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='order_status',
            field=models.CharField(choices=[('CA', 'Canceled'), ('SU', 'Submitted')], default='SU', max_length=2),
        ),
    ]
