# Generated by Django 4.1.3 on 2022-12-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_name',
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_en',
            field=models.CharField(default=0, max_length=100, verbose_name='category_name'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_fa',
            field=models.CharField(default=0, max_length=100, verbose_name='category_name'),
        ),
        migrations.AddField(
            model_name='products',
            name='description_en',
            field=models.TextField(default=0, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='products',
            name='description_fa',
            field=models.TextField(default=0, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_name_en',
            field=models.CharField(default=0, max_length=100, verbose_name='product_name'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_name_fa',
            field=models.CharField(default=0, max_length=100, verbose_name='product_name'),
        ),
    ]
