# Generated by Django 4.1.3 on 2022-12-05 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cake_designing', '0004_initial'),
        ('product', '0002_feeling_taste_orders_order_item_cake_designing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeling',
            name='basemodel_ptr',
        ),
        migrations.RemoveField(
            model_name='order_item',
            name='basemodel_ptr',
        ),
        migrations.RemoveField(
            model_name='order_item',
            name='discount_id',
        ),
        migrations.RemoveField(
            model_name='order_item',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='order_item',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='basemodel_ptr',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='discount_code_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='taste',
            name='basemodel_ptr',
        ),
        migrations.AlterField(
            model_name='discount',
            name='cake_designing_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cake_designing.cake_designing'),
        ),
        migrations.DeleteModel(
            name='Cake_Designing',
        ),
        migrations.DeleteModel(
            name='Feeling',
        ),
        migrations.DeleteModel(
            name='Order_Item',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Taste',
        ),
    ]
