# Generated by Django 4.1.3 on 2022-12-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_category_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name_en',
            field=models.CharField(max_length=100, verbose_name='category_name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name_fa',
            field=models.CharField(max_length=100, verbose_name='category_name'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description_en',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description_fa',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name_en',
            field=models.CharField(max_length=100, verbose_name='product_name'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name_fa',
            field=models.CharField(max_length=100, verbose_name='product_name'),
        ),
    ]
