# Generated by Django 4.1.3 on 2022-12-14 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_feeling_basemodel_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='category',
            field=models.ManyToManyField(to='product.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
    ]
