# Generated by Django 4.1.3 on 2023-01-01 15:53

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_category_category_name_en_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='discount_code',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
