# Generated by Django 4.1.3 on 2022-12-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_stock_category_alter_category_parent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, default='draw1.png', null=True, upload_to=''),
        ),
    ]
