# Generated by Django 4.1.3 on 2023-01-01 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_discount_code_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='discount_code',
            managers=[
            ],
        ),
    ]
