# Generated by Django 4.1.3 on 2022-12-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_category_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='after_discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='kilo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
