# Generated by Django 4.1.3 on 2022-12-14 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cake_designing', '0007_alter_cake_designing_description'),
        ('product', '0006_alter_stock_after_discount_alter_stock_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='cake_designing_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cake_designing.cake_designing'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='category_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.stock'),
        ),
    ]
