# Generated by Django 4.1.3 on 2022-12-14 14:20

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_discount_product'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='stock',
            managers=[
                ('stock_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
