# Generated by Django 4.1.3 on 2023-01-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_discount_code_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount_code',
            name='discount_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
