# Generated by Django 4.1.3 on 2023-01-01 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_discount_code_discount_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='discount_code',
            managers=[
            ],
        ),
    ]
