# Generated by Django 4.1.3 on 2022-12-15 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_discount_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='category_id',
        ),
    ]
